name: Lint

on:
  push:
    paths:
      - '**.kt'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: format kotlin
      run: ./gradlew formatKotlin

    - name: lint kotlin
      run: ./gradlew lintKotlin

    - name: Commit changes
      uses: EndBug/add-and-commit@v7
      with:
        message: '[Github Action - Lint] fix code format'
